### ISSUE TITLE
Game List not Alphabetical

### ISSUE THREAD

**Issue by snoogans775** [amusselm/rvgs_gamelist#23]
game list does not list alphabetical. will scale very poorly. the list will become massive regardless which is also an issue.

**Comment by amusselm** [comment]
Honestly, there's currently no place in the UI where users can access the global games list. That said, this is trivial to fix so I'll probably have a fix in the next commit.

**Comment by amusselm** [comment]
See also issue #22

**Comment by snoogans775** [comment]
this is in reference to the drop down box of games that comes up when searching for a game to add an achievement to

**Comment by amusselm** [comment]
Ah, yes. Not what I was thinking of but still an issue.

**Comment by amusselm** [comment]
It's now alphabetical in that screen. Resolving this issue.
